version: '3'
services:
  dns:
    image: coredns/coredns:1.7.0
    command:
      - "-conf"
      - "/etc/coredns/Corefile"
    restart: always
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
      - "8181:8181"
    volumes:
      - "./coredns/Corefile:/etc/coredns/Corefile:ro"
    links:
      - etcd
    depends_on:
      - etcd
  etcd:
    image: quay.io/coreos/etcd:v3.4.10
    command:
      - "etcd"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
  app:
    image: miyanonchi/myddns:v0.1.0
    restart: always
    environment:
      ETCD_HOST: etcd
      ETCD_PORT: 2379
      DDNS_DOMAIN: miyanet.local
    ports:
      - "0.0.0.0:8082:8082"
    links:
      - etcd
    depends_on:
      - etcd
